# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e04a6ca65df9ef61a3998a897c5e0edfb8e103356d463cbf1ee3590841f63835c30861d126f09e334fce3fa52e903d38175cf46b886f11127f91ce4909411a80

test:
  secret_key_base: d36fda01c88706e6c58a07029fa70e7420f1de4c65e0764419deb8033bae18b011d231b9151458a5fcdb866339905294fed7a164bf81bfe6ad2d150b41871611

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
